name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup yarn
      run: npm install -g yarn
    - name: Use Node.js ${{ matrix.node-version }} with yarn caching
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Run tests
      uses: koenhagen/measure-energy-action@v0.33
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn test
        count: 100
      
